// Code generated by sqlc. DO NOT EDIT.
// This lightweight stub mirrors sqlc output so the project builds without running sqlc.
package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

// User mirrors the users table.
type User struct {
	ID   int32     `json:"id"`
	Name string    `json:"name"`
	Dob  time.Time `json:"dob"`
}

type CreateUserParams struct {
	Name string
	Dob  time.Time
}

type UpdateUserParams struct {
	ID   int32
	Name string
	Dob  time.Time
}

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

// Queries exposes the generated query methods.
type Queries struct {
	db *pgxpool.Pool
}

// New creates a new Queries instance.
func New(db *pgxpool.Pool) *Queries {
	return &Queries{db: db}
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	const query = `INSERT INTO users (name, dob) VALUES ($1, $2) RETURNING id, name, dob`
	row := q.db.QueryRow(ctx, query, arg.Name, arg.Dob)
	var u User
	if err := row.Scan(&u.ID, &u.Name, &u.Dob); err != nil {
		return User{}, err
	}
	return u, nil
}

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	const query = `SELECT id, name, dob FROM users WHERE id = $1`
	row := q.db.QueryRow(ctx, query, id)
	var u User
	if err := row.Scan(&u.ID, &u.Name, &u.Dob); err != nil {
		return User{}, err
	}
	return u, nil
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	const query = `UPDATE users SET name = $2, dob = $3 WHERE id = $1 RETURNING id, name, dob`
	row := q.db.QueryRow(ctx, query, arg.ID, arg.Name, arg.Dob)
	var u User
	if err := row.Scan(&u.ID, &u.Name, &u.Dob); err != nil {
		return User{}, err
	}
	return u, nil
}

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	const query = `DELETE FROM users WHERE id = $1`
	_, err := q.db.Exec(ctx, query, id)
	return err
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	const query = `SELECT id, name, dob FROM users ORDER BY id LIMIT $1 OFFSET $2`
	rows, err := q.db.Query(ctx, query, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	users := make([]User, 0)
	for rows.Next() {
		var u User
		if err := rows.Scan(&u.ID, &u.Name, &u.Dob); err != nil {
			return nil, err
		}
		users = append(users, u)
	}
	return users, rows.Err()
}



